### ISSUE TITLE
[feature request] Allow changing all NKN port settings

### ISSUE THREAD

**Issue by markg85** [nknorg/nkn#695]
Hi,

Currently NKN allows to change much of the ports, but not the main "NodePort" (port 30001). This prohibits running multiple NKN nodes on a single IP.

Could this restriction be lifted to allow changing all ports thus in effect allow multiple nodes per ip?

I'm asking because in bigger cloud servers (but still one ip) you could very easily host multiple sites, databases, whatever... But only one NKN node.

Another case is company networks where they likely have one IP facing outwards, but tens to tens of thousands of "users". If that company happens to have a beefy internet connection only one user could run a NKN node.

Cheers,
Mark

**Comment by yilunzhang** [comment]
Actually this restriction was added during testnet.

The reason is quite straightforward: without such restrictions, the optimal strategy for everyone is to run as many nodes as possible. This will not bring any benefits to the network (although the node count looks larger) but will make the network unstable and insecure: normal people will simple throw many nodes until the machine can't hold it anymore, so even slight increase in traffic will make all those nodes to crash; attackers can easily launch hundreds (of not thousands) of nodes on a single machine and perform sybil attacks.

This is not just imagination, but has been observed during the early stage of the testnet. Currently restricting node port is the easiest way to prevent sybil attacks. We have always wanted a way that can achieve the same results without fixing the port, but I don't think there is a solution yet...

**Comment by markg85** [comment]
Thank you for the elaborate response!

That's a very valid concern, i hadn't thought about that one yet.

Ok, well, i will just close this then as it's not for now it seems.
