### ISSUE TITLE
apply cert failed: error 429. Rate limit with lets encrypt service

### ISSUE THREAD

**Issue by 12uler** [nknorg/nkn#760]
### Description of the issue
letsencrypt certificate service is rate limited.  Too many miners/certs issued? 
apply cert failed: error: 429

### Issue-Type (put a `x` sign in the square brackets)
- [ x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [ x] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS Raspbian/Docker
* Go version
* Release tag/commit of the code

### Expected behaviour
certificate is issued by letsencrypt

### Actual behaviour
letsencrypt is rate limited

### Steps to reproduce
1.  Setup and run a new miner. 
2.  run in docker using default settings. 

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
2021/04/10 20:33:52.480584 [ERROR] GID 82, apply cert failed: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many certificates already issued for: nknlabs.io: see https://letsencrypt.org/docs/rate-limits/

**Comment by 12uler** [comment]
Not sure if there is maybe an alternative certificate site we can use? I'm setting up a new miner and getting rate limit warnings. Should I ignore or is this a legit bug?

**Comment by yilunzhang** [comment]
You can ignore the warning as nknd will run normally without certificate. The certificate only affect js clients in https context, which are not common in network.

We have informed let's encrypt about this issue earlier this week, and they plan to increase the limit for our domain next week.

AFAIK let's encrypt is the only CA that can do this for free.

I'm closing this issue for now since it will be resolved next week. Feel free to re-open it if you need.
