### ISSUE TITLE
Can You guys please make it easier to update for christs sake

### ISSUE THREAD

**Issue by susLimbaugh** [nknorg/nkn#790]
This is ridiculous. Now that I have actually sunk money into your token to run a node, you guys update the next day and basically tell me update or the node is shot. MAKE IT EASIER TO UPDATE HOLY SHIT. IVE SPENT THE PAST 4 HOURS TRYING TO GIT FETCH AND MERGE AND EVERYTHING AND NOTHING WORKS! Is it so much to ask to not have to spend 8 hours fixing my node every time you guys release an update? Why is there not a function in nknc to auto update, this is complete bogus. Give me my money back you cowards. I want to support your chain but you're just making it so difficult for literally 0 reason.

**Comment by susLimbaugh** [comment]
or literally just an update function in nknc. absolutely 0 reason i should be going through this much trouble for so little reward. your blockchain literally will not survive unless you make improvements such as this

**Comment by yilunzhang** [comment]
There are many ways to deploy a node with auto update: nkn-commercial, nknx fast deploy, one-click, and many tutorials from community about how to make nknd auto-update. We won't make nknd/nknc auto update because any auto-update essentially depends on some centralized server. If the server is compromised and push some malicious code, all nodes will be compromised.

When you build from source, if you ever need to do git merge, rebase, or anything other than `git pull`, then you are doing something wrong. You are never supposed to do any of them. Normally you just need to do `git pull` and `make`, and that's it. If you accidentally modified anything, try `git checkout .` and then `git pull`. If you are not familiar enough with git, it might be easier just to deploy a node with auto update feature.

BTW, if you want to migrate to another deployment, you can move `wallet.json` and wallet password to the new node so no need to pay the generate ID fee again (but only one of them can be online at a time).

**Comment by susLimbaugh** [comment]
@yilunzhang got it, it was my mistake struggling to update, not you all. I misguided my frustration there, apologies. Keep doing what you're doing! :)
