### ISSUE TITLE
Unexpected JSON-RPC response format to `getwsaddr`

### ISSUE THREAD

**Issue by grondilu** [nknorg/nkn#852]
### Description of the issue

Trying to implement my own client, I noticed discrepancies between the response to `getwsaddr` and what is documented.

### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [ ] feature request
- [x] Documentation improvement

### Checklist
- [ ] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* GNU/linux, but that's irrelevant for this issue

### Expected behaviour
Response field "result" should be an url, as documented, not an object.

### Actual behaviour
Response was:
```json
{
  "id": "1",
  "jsonrpc": "2.0",
  "result": {
    "addr": "35.88.99.68:30002",
    "id": "b1dbbdbd143e7c13025842d241346c7ca15c2afbe51f7cead06bd35d162bb88b",
    "pubkey": "ea8e332b09d02c003b432dd95b2441fc8a2322418abcccc2da35450809f8acbf",
    "rpcAddr": "35.88.99.68:30003"
  }
}
```
I suppose the websocket address I need is in the `addr` field, but what is `id`?  And why giving a pubkey at this point, before I even established the connection?

### Steps to reproduce

    curl -s -X POST -d '{ "params" : { "address" : "anon.767068306aa02c60276281dc29168bb0191403fc595e3cf1a4dcf350aa86ea75" }, "method" : "getwsaddr" }' http://mainnet-seed-0015.nkn.org:30003

**Comment by yilunzhang** [comment]
We have updated the doc so it matches the actual response.

> I suppose the websocket address I need is in the addr field

Yes that's right.

> but what is id?

Each node has a unique ID. It's used for packet routing and is also a counter sybil mechanism. SDK side doesn't really need to know or worry about it.

> And why giving a pubkey at this point, before I even established the connection?

On the contrary, knowing public key before establishing a connection is the only way to guarantee end to end safety, and that's why you need a CA issued certificate in TLS. For now this field is not being used, but in the future it could be useful if we want to implement another layer of encryption between client and node.
