### ISSUE TITLE
Build from Source: add Documentation re Testing

### ISSUE THREAD

**Issue by abebeos** [nknorg/nkn#888]
The README and WIKI do not contain documentation on how to run tests:

https://github.com/nknorg/nkn#building-from-source

A very old issue re `make test` is still open #258.

## Expected

* `make test` should be functioning and documented
* a public CI is available that executes the tests (see #890)

## Solution

This seems to work:

```sh
# on alpine:
apk add g++

# run all tests
go test -v ./...
```

## Test Failures

- #891
- #892

**Comment by yilunzhang** [comment]
That's something we are still working on. Currently tests are mainly done by automatic build + manual integrated test because most of the functions in nkn are not designed for single node. You will need to launch like a dozen nodes to actually do the tests. We have an automatic devnet that will test the latest code in a small cluster with some basic functions like sending txn, consensus, etc, but it's far from complete yet

**Comment by abebeos** [comment]
I understand that your integration testing is currently internal, but I see no reason to not have basic unit tests available.

Can we agree to this as a first step to get 

* map `make test` to `go test -v ./...`
* fix or disable failing tests
* document those basic tests
* add them to the CI (build&test run)
